name: Update index.html

on:
  #schedule:
    # Run once every 5 minutes (GitHub Actions' minimum interval)
   # - cron: "*/5 * * * *"
  push:
    branches: 
    - master # Trigger the workflow on push to the main branch

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rubenpp7.github.io repo
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies from Repo B
      run: |
        # Install remotes if it's not installed yet
        R -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
        # Install the R package from Repo B (replace with the correct username/repo)
        R -e 'remotes::install_github("rubenpp7/divewatchr")'

    - name: Run R function from Repo B
      run: |
        Rscript -e 'library(divewatchr); divewatch(data = "1qO7_0K1R-4i_MSgtT3zAYbZfxBmPMgQWAi7OmWmb1-M")'

    - name: Rename old index.html
      run: |
        if [ -f "index.html" ]; then
          mv index.html index_old.html
        fi

    - name: Rename output.html to index.html
      run: |
        if [ -f "overview.html" ]; then
          mv overview.html index.html
        fi

    - name: Commit changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html index_old.html
        git commit -m "Update index.html and rename old file"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
